import { Router } from 'express';
import authRoutes from './authRoutes';
import tenantRoutes from './tenantRoutes';
import userRoutes from './userRoutes';
import auditRoutes from './auditRoutes';
import dashboardRoutes from './dashboardRoutes';
import leadRoutes from './leadRoutes';
import taskRoutes from './taskRoutes';
import productRoutes from './productRoutes';
import groupRoutes from './groupRoutes';
import formRoutes from './formRoutes';
import aiRoutes from './aiRoutes';
import calendarRoutes from './calendarRoutes';
import healthRoutes from './healthRoutes';
import searchRoutes from './searchRoutes';
import billingRoutes from './billingRoutes';
import { productGroupsForProductRouter, productGroupRouter } from './productGroupsRoutes';
import { authenticate } from '../middleware/auth';
import { tenantGuard } from '../middleware/tenant';

const router = Router();

router.use('/', healthRoutes);
router.use('/auth', authRoutes);
router.use('/tenants', tenantRoutes);
router.use('/users', userRoutes);
router.use('/audit', auditRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/leads', leadRoutes);
router.use('/tasks', taskRoutes);
router.use('/products', productRoutes);
router.use('/products/:productId/groups', authenticate, tenantGuard, productGroupsForProductRouter);
router.use('/product-groups', authenticate, tenantGuard, productGroupRouter);
router.use('/groups', groupRoutes);
router.use('/forms', formRoutes);
router.use('/ai', aiRoutes);
router.use('/calendar', calendarRoutes);
router.use('/search', searchRoutes);
router.use('/billing', billingRoutes);

export default router;
